version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    depends_on :
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:  ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rmonney/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rmonney/data/mariadb

networks:
   inception:
       driver: bridge
